# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "BigTinaBang"
description: > # this means to ignore newlines until "email:"
   爱读书，爱跳舞，做一首文艺范儿的前端攻城诗

email: me@bigtinabang.com
#blog logo
logo: "/assets/images/logo.png"
logob: "/assets/images/logob.jpg"
# blog cover
cover: "/assets/images/banner.jpg"

name: 'BigTinaBang'
author: 'Tina Chen'
author_image: "/assets/images/author.png"

paginate:	5

url: "http://bigtinabang.com" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	http://www.weibo.com/u/1291261522
    desc: Follow me on weibo
    share_url: http://weibo.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/TinaC
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
